### ISSUE TITLE
Create Github Actions

### ISSUE THREAD

**Issue by martinGM05** [martinGM05/Code-Challenge#8]
Create the path: `.github/workflows/test.yml` and write:

```yml
name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
```
